apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lkdm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lkdm
    app.kubernetes.io/part-of: ci1t-830-0060-app
  name: devfile-sample-lkdm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lkdm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lkdm
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0060-tenant/ci1t-830-0060-app/devfile-sample-lkdm@sha256:96afafeaad1e8f92c7ddc5c1a59ce36f9653a0a9cf70fa582dd03f4a5d6c1e2b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
